[package]
name = "vylrhg"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["rt-multi-thread", "macros", "fs", "time", "signal", "io-util", "io-std", "sync"] }
